### ISSUE TITLE
Routing - https://rnbw.dev/folder-name/file-name.*

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#176]
Motivation
- better navigation, ability to open a project from the address bar
- analytics, we can better track and then understand how users take advantage of it and their session times.
- ...

**Comment by atulbhatt-system32** [comment]
@edenvidal for using routing to open a project just using folder name won't be enough.

We will also have to know which drive the project is loaded from or which outer folder. Because we can't directly know the full path of a project just by using the relative path.

Though navigation can definitely be used to detect which file to open by default when the project loads.

**Comment by edenvidal** [comment]
@atulbhatt-system32 correct me if im wrong, but i think there are two things
1. the routing of the project for once it is opened in rnbw and has a route
2. the local route.

so, while i don't think we need to be able to open a local folder/file throughout rnbw in that way. there should be some way to do that, which can be https://rnbw.dev?localhost/folder-name/file-name.* and this can initiate rnbw to ask for folder opening.

**Comment by atulbhatt-system32** [comment]
@edenvidal yeah we can do that. I get it now. We will just use it to open a project. Kinda linking it with VS code extension.

**Comment by edenvidal** [comment]
exactly! this is the endpoint for external stuff like vscode too

**Comment by atulbhatt-system32** [comment]
@edenvidal I was checking the filesystem api and there isn't a way to implicitly open a directory or even start showing a directory directly. It will always work manually because of the security concern.

Though I will research more deeply into it.

**Comment by edenvidal** [comment]
@atulbhatt-system32 the security concern is applied as the dialogue would still appear whenever opening a new 'yet to confirmed' folder. i think we'll need to create a functionality that triggers the (existing) request into receiving a folder/file route.

**Comment by atulbhatt-system32** [comment]
@edenvidal the point is that filesystem api doesn't allow to open a folder directly programmatically.

We can only trigger the opening of `file picker dialogue` but not which location the `dialogue` will open in.

This is a limitation which we have from the api.

**Comment by edenvidal** [comment]
i see what you mean. tbd @atulbhatt-system32

**Comment by edenvidal** [comment]
@atulbhatt-system32 @jasonliu7040 let's restart this task.

When it comes to routing, it's important to note that it doesn't represent the actual local file system. The routing instead represents the currently opened projects that are stored under the local storage. Once a project is open, there should be a way to access it through an address. https://rnbw.dev/main-folder-name/file-folder-name/file-folder-name.*#176

**Comment by VictoriaShyika** [comment]
Routing task:

1) If the URL has a project that is included in the recent projects list, then be able to open them.

Opening recent projects via URL:
Due to the security of the browser, we cannot open another project through the URL of the browser, because interaction with the user interface is necessary.

So in order to open another project in this way, it is necessary to add interaction with the interface, for example (create a modal (opens after typing something in URL and Enter press) by clicking on which the necessary project will be opened, however standard confirm, alert, prompt are not suitable).

Now, without user interaction with the interface, when importing files, validation does not take place and the import does not take place.

2) Navigation on the open project;

Navigation on an open project via URL works correctly and will not require any improvements.

**Comment by edenvidal** [comment]
@VictoriaShyika thanks! I guess the question is - while rnbw is initially loading, can certain routing trigger the request to open a certain folder? with the system modal, of course, for the permission, as always?

**Comment by atulbhatt-system32** [comment]
@VictoriaShyika so is it possible to launch an alert box to tell them they will be asked for permission and then when they press ok we can trigger the permission dialog (files)?

**Comment by VictoriaShyika** [comment]
@atulbhatt-system32  yes, but alert box should be not system (I tried with alert and confirm its not work)

**Comment by atulbhatt-system32** [comment]
Okay then you can start with checking OPFS with minimal setup if it is practical to use it in rnbw

**Comment by edenvidal** [comment]
@VictoriaShyika @atulbhatt-system32 I see the constraints in opening local files.
for now, let's fully implement the routing mechanism so that the URL will fully reflect the currently active file. later, in the context of the [vs-code-extension task](https://github.com/rnbwdev/rnbw-vscode/issues/1#issue-1786329226), we can implement a modal/notification system for such things.

**Comment by atulbhatt-system32** [comment]
okay sure @edenvidal
