### ISSUE TITLE
Code in the code view should look neat, or prettified after any operation like add, remove, delete node, etc.

### ISSUE THREAD

**Issue by atulbhatt-system32** [rnbwdev/rnbw#357]
Find out if there's native way for monaco editor to figure out we are using html and accordingly do the formatting.

**Comment by VictoriaShyika** [comment]
Monaco editor native formatting does not provide formatting. 
For using Prettier we need server.

Because of that was formatting tools were studied and js-beautify was selected.
js-beautify is a tool that can beautify and format code in various programming languages, for example: JavaScript (js), JSON (json), HTML (html, htm), XML (xml), Markdown (md, markdown), CSS (css), Sass (scss), Less (less), TypeScript (ts), JSX (jsx), Angular (ng), Vue.js (vue), Handlebars (hbs), GraphQL (graphql), YAML (yaml, yml).

What we need to implement:
- Implement a Command Palette Toggle for formatting with Default option false 
- Enable Code Formatting Toggle with Command Palette or Shortcut (Ctrl + Shift + F)
