### ISSUE TITLE
live sync (doesn't work)

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#556]
- [ ] Files should be responsive to local changes and fetch them, allowing for real-time updates of the active page while retaining the focus on the active element.

**Comment by atulbhatt-system32** [comment]
@edenvidal
Would need steps to see how you operated to find out when it's not working.

The operations can be edit, delete, add, etc.

This can help in streamlining the cause and fix it soon.

**Comment by edenvidal** [comment]
@atulbhatt-system32 

1. delete a file locally from your system using rnbw.
2. confirm that the file is also deleted locally.
3. Attempt to bring the deleted file back locally using Git.
4. Verify that the file is restored in your local folder.
5. Observe that the file restoration is not reflected in "rnbw."

**Comment by atulbhatt-system32** [comment]
@edenvidal I did the same steps and the file was restored. So a video might help whenever you get time to upload it.

**Comment by atulbhatt-system32** [comment]
So it turns out that the " visibilityChange " event that we use to trigger file sync doesn't work when the browser is visible. So when users can perform the file deletion from wherever they can, it won't trigger the file sync.

Now, the better approach should have been to use "onFocus" and "onBlur" but there are some caveats with it. They provide false detection. For example: if an `alert` dialog box opens, it triggers an "onBlur" event even though the rnbw application is in "Focus".

Now, the other issue with this approach is with Stage.

This is really tricky. There seems to be no solution given the following requirements.

The page includes iframes that you have no control over (Though we have control over it : stage)
You want to track visibility state change regardless of the change being triggered by a TAB change (ctrl+tab) or a window change (alt+tab)
This happens because:

The page Visibility API can reliably tell you of a tab change (even with iframes), but it can't tell you when the user changes windows.
Listening to window blur/focus events can detect alt+tabs and ctrl+tabs, as long as the iframe doesn't have focus.
Given these restrictions, it is possible to implement a solution that combines - The page Visibility API - window blur/focus - document.activeElement

That can:

1) ctrl+tab when parent page has focus: YES
2) ctrl+tab when iframe has focus: YES
3) alt+tab when parent page has focus: YES
4) alt+tab when iframe has focus: NO <-- bummer
When the iframe has focus, your blur/focus events don't get invoked at all, and the page Visibility API won't trigger on alt+tab.

So we will have to add "onFocus" and "onBlur" on stage too.
