### ISSUE TITLE
design / canvas-mode

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#772]
- [x] toggled when zooming in and out of a page.
- [x] esc exits canvas mode as well as the other things it does

- [x] keyboard shortcuts 1-0
  - [x] 1-10% zoom
  - [x] 9-90% zoom
  - [x] 0-100% zoom. 100% viewport mode (toggle with esc or "0")
  - [x] 150 - 150%
  - [x] extra: shortcuts + / - / 25% more/less. defaults to it's closest 25 count pattern. 25/50/75/100/...

by default, it is 100% viewport, and the scroll behavior is coherent with the page. (which is the existing behavior)
when zooming in/out, the zoom-mode starts and the scroll (x/y) is within a 'canvas' context.

- [x] remove the existing zoom in/out completely.
- [x] remove any zoom in/out from the app (check how figma canceled it).

**Comment by edenvidal** [comment]
@maxdnc, check this out.

**Comment by vicki29** [comment]
For this task was created [PR](https://github.com/rnbwdev/rnbw/pull/864).

Next things need to improve :
- Zoom issue: When zooming the canvas, when the Iframe (design view) changes to a container under the cursor, the entire page scales unexpectedly. (Maybe its happens because IFrame, but I not find the issue resolving).
- Position issue: The design view should be on canvas center.
- When zoom in, the design becomes larger than the canvas, part of the design page goes beyond the canvas container and we can't access it with the scroll.
