### ISSUE TITLE
Content inside head tag like css, style, script don't update until the page is reloaded

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#779]

**Comment by edenvidal** [comment]
@atulbhatt-system32 can you describe?

**Comment by atulbhatt-system32** [comment]
We use morphdom to update our stage automatically whenever we do any changes in our code. We use morphdom because it does dom-diffing internally and updates the stage without refreshing.

We can't process anything inside head tag using it. Changing JS is like restarting every JS that is loaded in the page everytime any change in the code is done related to it.

We can deploy the same technique for external JS file. Those loaded from external file similar to what we did in css but it will take time to implement and test.

**Comment by edenvidal** [comment]
@atulbhatt-system32 recorded a video regarding js not having a choice but rendering the entire page - which is actually a good thing! let's do that. and re-render the entire page, and deal with the issues that may come with it like "selection". see recorded video.

**Comment by edenvidal** [comment]
@atulbhatt-system32 what's our status with this? thanks 🙏

**Comment by atulbhatt-system32** [comment]
@edenvidal Now this works!! The script tag reload and for others it refreshes
