### ISSUE TITLE
rnbw doesn't recognize </br>

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw#825]
For some reason, I can't upload the video here today, so it's available via the link
https://drive.google.com/file/d/1FTsVThLGEkqTSQnfhbA7Bl7SXZmDeAOa/view?usp=share_link

**Comment by atulbhatt-system32** [comment]
<br/> is there but it is am empty tag so takes no width that's why you don't see it on stage. Try to check the nodeTree you will find LineBreak.

To show it visually we will need to handle it manually

**Comment by edenvidal** [comment]
@atulbhatt-system32 wdyt. eventually it is something deeper, right?

**Comment by atulbhatt-system32** [comment]
Like we need to understand how to handle this do we give some height and width to these type of tags

**Comment by edenvidal** [comment]
how is it related? i need to know more 🙏

**Comment by atulbhatt-system32** [comment]
> how is it related? i need to know more 🙏

@edenvidal Firstly I don't understand the problem here as shown in the video. My speculation is you are unable to see <br/> tag on stage.

Though, it doesn't mean rnbw is not recognizing it. It is there on the nodeTree as well as on stage but it has not content in it hence no height and width that's why we are unable to select it.
